apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'spring'
      metrics_path: 'actuator/prometheus'
      static_configs:
        - targets: ['tech.devops2022.de:5000']
