apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5m
      scrape_timeout: 1m
      evaluation_interval: 1m

    scrape_configs:
    - job_name: 'spring-actuator'
      scheme: https
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['tech.devops2022.de:8080']
