apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 1m
      scrape_timeout: 30s
      evaluation_interval: 30s

    scrape_configs:
    - job_name: 'spring-actuator'
      scheme: https
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['tech.devops2022.de:8080']
