apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 15s
      evaluation_interval: 15s

    # scrape_configs:
    # - job_name: 'springboot'
    #   metrics_path: '/actuator/prometheus'
    #   static_configs:
    #     - targets: ['backend-service:5000']
    scrape_configs:
    - job_name: 'backend-counter'
      metrics_path: '/management/prometheus'
      scheme: 'http'
      static_configs:
        - targets: ['backend-service:8081']
    # scrape_configs:
    # - job_name: 'nginx'
    #   scrape_interval: 5s
    #   static_configs:
    #     - targets: ['hellow-world:80'] # Replace with the actual service name and port
    #   metrics_path: /metrics
    #   params:
    #     module: [nginx]
    #   relabel_configs:
    #     - source_labels: [__address__]
    #       target_label: __param_target
    #     - source_labels: [__param_target]
    #       target_label: instance
    #     - target_label: __address__
    #       replacement: nginx-exporter:9113 # Replace with the actual exporter name and port

