apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 30s
      scrape_timeout: 15s
      evaluation_interval: 15s

    scrape_configs:
    - job_name: 'springboot'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['20.71.83.112:8080']
