apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/postgres-configmap.yaml
- k8s/postgres-deploy.yaml
- k8s/postgres-secret.yaml
- k8s/postgres-service.yaml
- k8s/backend.yaml
images:
- name: devops2022.azurecr.io/tech
  newTag: 4df00c51497acd44fd7665a1ecbd3e0fa74ec844
