apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/postgres-configmap.yaml
- k8s/postgres-deploy.yaml
- k8s/postgres-service.yaml
- k8s/pgadmin-deploy.yaml
- k8s/pgadmin-service.yaml
- k8s/backend.yaml
- k8s/kibana.yaml
- k8s/sonarqube.yaml
images:
- name: devops2022.azurecr.io/teamtechbackend
  newTag: e3c41cee7f2d5017504c0d3b610f27232c1bce95
- name: devops2022.azurecr.io/tech
  newTag: e3c41cee7f2d5017504c0d3b610f27232c1bce95
