apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/ingress.yaml
images:
- name: devops2022.azurecr.io/eslamk8s
  newTag: 22be2f62a1701a3113d99911dd96d34e96047964
