apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/postgres-configmap.yaml
- k8s/postgres-deploy.yaml
- k8s/postgres-service.yaml
- k8s/pgadmin-deploy.yaml
- k8s/pgadmin-service.yaml
- k8s/backend.yaml
- k8s/kibana.yaml
images:
- name: devops2022.azurecr.io/teamtechbackend
  newTag: a3ff04e2bb9682705ea2fb551e1ba16b7088384a
- name: devops2022.azurecr.io/tech
  newTag: a3ff04e2bb9682705ea2fb551e1ba16b7088384a
