apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/DB/postgres-configmap.yaml 
- k8s/DB/postgres-deploy.yaml
- k8s/DB/postgres-service.yaml
- k8s/DB/pgadmin-deploy.yaml
- k8s/DB/pgadmin-service.yaml
- k8s/backend.yaml
- k8s/kibana.yaml
- k8s/sonarqube-1.yaml
- k8s/prometheus/prom-deployment.yaml
- k8s/prometheus/prometheus-config.yaml
- k8s/prometheus/prometheus-service.yaml
images:
- name: devops2022.azurecr.io/teamtechbackend
  newTag: 07051451ba219aeb467d2814249bbfe75bce18a5
- name: devops2022.azurecr.io/tech
  newTag: 07051451ba219aeb467d2814249bbfe75bce18a5
