apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/ingress.yaml
images:
- name: devops2022.azurecr.io/tech
  newTag: 42fe325ccf5d480f96674eb93f0d376aa16452b0
