apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/postgres-configmap.yaml
- k8s/postgres-deploy.yaml
- k8s/postgres-service.yaml
- k8s/pgadmin-deploy.yaml
- k8s/pgadmin-service.yaml
- k8s/backend.yaml
- k8s/kibana.yaml
- k8s/sonarqube-1.yaml
images:
- name: devops2022.azurecr.io/teamtechbackend
  newTag: c0c0d277d9a1a18c919eb4855b5e3e5179a7fac7
- name: devops2022.azurecr.io/tech
  newTag: c0c0d277d9a1a18c919eb4855b5e3e5179a7fac7
