apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/prom-service.yaml
- k8s/postgres-configmap.yaml
- k8s/postgres-deploy.yaml
- k8s/postgres-service.yaml
- k8s/pgadmin-deploy.yaml
- k8s/pgadmin-service.yaml
- k8s/backend.yaml
- k8s/kibana.yaml
- k8s/sonarqube.yaml
images:
- name: devops2022.azurecr.io/teamtechbackend
  newTag: 90cf869d298a83d632eb026d222b0bf1291b8bf1
- name: devops2022.azurecr.io/tech
  newTag: 90cf869d298a83d632eb026d222b0bf1291b8bf1
