apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/postgres-configmap.yaml
- k8s/postgres-deploy.yaml
- k8s/postgres-secret.yaml
- k8s/postgres-service.yaml
images:
- name: devops2022.azurecr.io/tech
  newTag: 551257173437fc85e6484dfffe323aa036e08e22
