apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/DB/postgres-configmap.yaml
- k8s/DB/postgres-deploy.yaml
- k8s/DB/postgres-service.yaml
- k8s/DB/pgadmin-deploy.yaml
- k8s/DB/pgadmin-service.yaml
- k8s/backend.yaml
- k8s/kibana.yaml
- k8s/sonarqube-1.yaml
- k8s/prometheus/prom-deployment.yaml
- k8s/prometheus/prometheus-config.yaml
- k8s/prometheus/prometheus-service.yaml
- k8s/Grafana/grafana-datasource-config.yaml
- k8s/Grafana/grafana-deployment.yaml
- k8s/Grafana/grafana-service.yaml
- k8s/Nagios/nagios.deployment.yaml
- k8s/Nagios/nagios-service.yaml
images:
- name: devops2022.azurecr.io/teamtechbackend
  newTag: 35dc63939feab7d78c58bad08725df743726006a
- name: devops2022.azurecr.io/tech
  newTag: 35dc63939feab7d78c58bad08725df743726006a
