apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- k8s/ingress.yaml
- k8s/nginx-deployment.yaml
- k8s/nginx-service.yaml
- k8s/postgres-configmap.yaml
- k8s/postgres-deploy.yaml
- k8s/postgres-service.yaml
- k8s/pgadmin-deploy.yaml
- k8s/pgadmin-service.yaml
- k8s/backend.yaml
- k8s/kibana.yaml
- k8s/sonarqube.yaml
- k8s/kube-prometheus-stack/Chart.yaml
images:
- name: devops2022.azurecr.io/teamtechbackend
  newTag: 90c5bd85bcd330599d3e077ff1b15515e0565ce3
- name: devops2022.azurecr.io/tech
  newTag: 90c5bd85bcd330599d3e077ff1b15515e0565ce3
