apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: teamtech-ns
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  type: LoadBalancer  
  ports:
    - port: 3000
  selector: 
    app: grafana
      