apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tech-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  tls:
    - hosts:
      - tech.devops2022.de
      - kibana.weatherapp.devops2022.de
      secretName: tech-prod-tls
  rules:
  - host: tech.devops2022.de
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: hello-world
              port:
                number: 80
        - pathType: Prefix
          path: "/postgres"
          backend:
            service:
              name: postgres
              port: 
                number: 30432
        - pathType: Prefix
          path: "/booking"
          backend:
            service:
              name: backend-service
              port:
                number: 5000
        - pathType: Prefix
          path: "/alive"
          backend:
            service:
              name: backend-service
              port:
                number: 5000
  - host: kibana.tech.devops2022.de
    http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: tech-kibana-kb-http 
              port:
                number: 5601
        
                
