apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: tech-kibana
spec:
  version: 7.10.0
  count: 1
  elasticsearchRef:
    namespace: logging
    name: quickstart
  http:
    service:
      metadata:
        name: teamtech-kibana
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      spec:
        type: LoadBalancer
        ports:
        - port: 5601
          protocol: TCP
          targetPort: 5601