apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: tech-kibana
spec:
  version: 7.10.0
  count: 1
  elasticsearchRef:
    namespace: logging
    name: quickstart
  http:
    service:
      metadata:
        name: teamtech-kibana
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
      spec:
        type: LoadBalancer
        ports:
        - port: 5601
          protocol: TCP
          targetPort: 5601
    tls:
      selfSignedCertificate:
        subjectAltNames:
          - dns: kibana.tech.devops2022.de
