apiVersion: v1
kind: Service
metadata: 
  name: hello-world
  labels:
    app: teamtech
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    protocol: TCP
    targetPort: 80
  - port: 9113
    targetPort: 9113
  selector:
    app: teamtech
