apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: teamtech-ns
data:
  nginx.conf: |
    worker_processes 1;
    events {
      worker_connections 1024;
    }
    http {
      default_type text/css; 
      server {
        location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
        }
        location /nginx_status {
          stub_status on;
          access_log off;
        }
      }
    }