apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-deployment
  labels:
    app: teamtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teamtech
  template:
    metadata:
      labels:
        app: teamtech
    spec:
      containers:
      - name: nginx
        image: devops2022.azurecr.io/tech:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-metrics-config
          mountPath: /etc/nginx/conf.d/nginx.conf
          subPath: nginx.conf
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter
        args:
        - '-nginx.scrape-uri=http://20.31.107.48:80/nginx_status'
        ports:
        - containerPort: 9113
        readinessProbe:
          httpGet:
            path: /metrics
            port: 9113
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-metrics-config
        configMap:
          name: nginx-metrics-config

