---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-prometheus-service-monitor
  namespace: teamtech-ns
spec:
  selector:
    matchLabels:
      app: teamtech
  endpoints:
  - interval: 5s
    port: nginx-prometheus-exporter
    path: /metrics