apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          env:
          - name: PGADMIN_DEFAULT_EMAIL
            value: "eabdien@web.de"
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgadmin-secret
                key: pgadmin-default-password
          - name: PGADMIN_PORT
            value: "80"
          - name: PGADMIN_CONFIG_FILE
            value: /pgadmin4/config_local.py
          volumeMounts:
            - name: pgadmin-config
              mountPath: /pgadmin4
          ports:
            - containerPort: 80
              name: pgadminport
      volumes:
      - name: pgadmin-config
        configMap:
          name: pgadmin-config
